#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-x86-32

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: SSR
        run: |
          cd package
          mkdir openwrt-packages
          cd openwrt-packages
          git clone https://github.com/fw876/helloworld.git

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # ========================固件定制部分========================
          # 

          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 

          # 以下为定制化固件选项和说明:
          #

          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #

          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 

          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_generic=y
          CONFIG_TARGET_x86_generic_Generic=y
          # CONFIG_TARGET_x86=y
          # CONFIG_TARGET_x86_64=y
          # CONFIG_TARGET_x86_64_Generic=y
          EOF

          # 固件压缩:
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_TARGET_KERNEL_PARTSIZE=30
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          EOF

          # 编译UEFI固件:
          cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          EOF

          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          EOF

          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          EOF

          # USB3.0支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          EOF

          # 常用LuCI插件选择:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-hd-idle=y
          CONFIG_PACKAGE_luci-app-kodexplorer=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Simple_obfs=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_ddns-scripts_dnspod=y
          CONFIG_PACKAGE_ddns-scripts_aliyun=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-aria2=y
          CONFIG_PACKAGE_luci-app-docker=y
          CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl2030=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl3160=y
          CONFIG_PACKAGE_iwlwifi-firmware-iwl7260=y
          CONFIG_PACKAGE_kmod-rtl8192c-common=y
          CONFIG_PACKAGE_kmod-rtl8192ce=y
          CONFIG_PACKAGE_kmod-rtl8192cu=y
          CONFIG_PACKAGE_kmod-rtl8192de=y
          CONFIG_PACKAGE_kmod-rtl8192se=y
          CONFIG_PACKAGE_kmod-rtl8723bs=y
          CONFIG_PACKAGE_kmod-rtlwifi=y
          CONFIG_PACKAGE_kmod-rtlwifi-pci=y
          CONFIG_PACKAGE_kmod-rtlwifi-usb=y
          CONFIG_PACKAGE_kmod-usb-serial-ark3116=y
          CONFIG_PACKAGE_rt2800-pci-firmware=y
          CONFIG_PACKAGE_rt61-pci-firmware=y
          CONFIG_PACKAGE_rt73-usb-firmware=y
          CONFIG_PACKAGE_rtl8188eu-firmware=y
          CONFIG_PACKAGE_rtl8192ce-firmware=y
          CONFIG_PACKAGE_rtl8192cu-firmware=y
          CONFIG_PACKAGE_rtl8192de-firmware=y
          CONFIG_PACKAGE_rtl8192eu-firmware=y
          CONFIG_PACKAGE_rtl8192se-firmware=y
          CONFIG_PACKAGE_rtl8192su-firmware=y
          CONFIG_PACKAGE_rtl8723au-firmware=y
          CONFIG_PACKAGE_rtl8723bu-firmware=y
          CONFIG_PACKAGE_rtl8821ae-firmware=y
          CONFIG_PACKAGE_rtl8822be-firmware=y
          CONFIG_PACKAGE_rtl8822ce-firmware=y
          CONFIG_PACKAGE_kmod-usb-net-asix=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8150=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_kmod-usb-net-dm9601-ether=y
          CONFIG_PACKAGE_kmod-rt2500-usb=y
          CONFIG_PACKAGE_kmod-rt2800-lib=y
          CONFIG_PACKAGE_kmod-rt2800-usb=y
          CONFIG_PACKAGE_kmod-rt2x00-lib=y
          CONFIG_PACKAGE_kmod-rt2x00-usb=y
          CONFIG_PACKAGE_kmod-rt73-usb=y
          CONFIG_PACKAGE_kmod-rtl8187=y
          CONFIG_PACKAGE_kmod-rtl8192c-common=y
          CONFIG_PACKAGE_kmod-rtl8192cu=y
          CONFIG_PACKAGE_kmod-net-rtl8188eu=y
          CONFIG_PACKAGE_kmod-net-rtl8192su=y
          CONFIG_PACKAGE_ath10k-firmware-qca9888=y
          CONFIG_PACKAGE_ath10k-firmware-qca988x=y
          CONFIG_PACKAGE_ath10k-firmware-qca9984=y
          CONFIG_PACKAGE_ath9k-htc-firmware=y
          CONFIG_PACKAGE_bnx2-firmware=y
          CONFIG_PACKAGE_bnx2x-firmware=y
          CONFIG_PACKAGE_e100-firmware=y
          CONFIG_PACKAGE_r8169-firmware=y
          CONFIG_PACKAGE_rt2800-usb-firmware=y
          CONFIG_PACKAGE_kmod-usb-net=y
          CONFIG_PACKAGE_kmod-usb-net-asix=y
          CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-eem=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-mbim=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
          CONFIG_PACKAGE_kmod-usb-net-cdc-subset=y
          CONFIG_PACKAGE_kmod-usb-net-dm9601-ether=y
          CONFIG_PACKAGE_kmod-usb-net-hso=y
          CONFIG_PACKAGE_kmod-usb-net-huawei-cdc-ncm=y
          CONFIG_PACKAGE_kmod-usb-net-ipheth=y
          CONFIG_PACKAGE_kmod-usb-net-kalmia=y
          CONFIG_PACKAGE_kmod-usb-net-kaweth=y
          CONFIG_PACKAGE_kmod-usb-net-mcs7830=y
          CONFIG_PACKAGE_kmod-usb-net-pegasus=y
          CONFIG_PACKAGE_kmod-usb-net-pl=y
          CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
          CONFIG_PACKAGE_kmod-usb-net-rndis=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8150=y
          CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
          CONFIG_PACKAGE_kmod-usb-net-sierrawireless=y
          CONFIG_PACKAGE_kmod-usb-net-smsc95xx=y
          CONFIG_PACKAGE_kmod-usb-net-sr9700=y
          CONFIG_PACKAGE_kmod-switch-ip17xx=y
          CONFIG_PACKAGE_kmod-switch-mvsw61xx=y
          CONFIG_PACKAGE_kmod-switch-rtl8306=y
          CONFIG_PACKAGE_kmod-switch-rtl8366-smi=y
          CONFIG_PACKAGE_kmod-switch-rtl8366rb=y
          CONFIG_PACKAGE_kmod-switch-rtl8366s=y
          CONFIG_PACKAGE_kmod-switch-rtl8367b=y
          CONFIG_PACKAGE_kmod-r6040=y
          CONFIG_PACKAGE_kmod-r8169=y
          CONFIG_PACKAGE_kmod-rt2800-lib=y
          CONFIG_PACKAGE_kmod-rt2800-usb=y
          CONFIG_PACKAGE_kmod-rt2x00-lib=y
          CONFIG_PACKAGE_kmod-rt2x00-usb=y
          CONFIG_PACKAGE_kmod-mac80211=y
          CONFIG_PACKAGE_kmod-macvlan=y
          CONFIG_PACKAGE_kmod-dm=y
          CONFIG_PACKAGE_kmod-dm9000=y
          CONFIG_PACKAGE_nginx=y
          CONFIG_PACKAGE_nginx-mod-luci=y
          CONFIG_PACKAGE_shadow-useradd=y
          CONFIG_PACKAGE_shadow-groupadd=y
          CONFIG_PACKAGE_spawn-fcgi=y	
          CONFIG_PACKAGE_mariadb-server=y	
          CONFIG_PACKAGE_libmysqlclient=y	
          CONFIG_PACKAGE_ibncursesw=y	
          CONFIG_PACKAGE_uclibcxx=y	
          CONFIG_PACKAGE_libreadline=y	
          CONFIG_PACKAGE_libncurses=y	
          CONFIG_PACKAGE_wget=y	
          CONFIG_PACKAGE_unzip=y	
          CONFIG_PACKAGE_grep=y	
          CONFIG_PACKAGE_sed=y	
          CONFIG_PACKAGE_tar=y	
          CONFIG_PACKAGE_ca-certificates=y	
          CONFIG_PACKAGE_coreutils-whoami=y	
          CONFIG_PACKAGE_php7=y	
          CONFIG_PACKAGE_php7-cgi=y	
          CONFIG_PACKAGE_php7-cli=y	
          CONFIG_PACKAGE_php7-fastcgi=y	
          CONFIG_PACKAGE_php7-fpm=y	
          CONFIG_PACKAGE_php7-mod-mysqli=y	
          CONFIG_PACKAGE_php7-mod-pdo=y	
          CONFIG_PACKAGE_php7-mod-pdo-mysql=y	
          CONFIG_PACKAGE_nginx-extras=y	
          CONFIG_PACKAGE_mariadb-server=y	
          CONFIG_PACKAGE_mariadb-server-extra=y	
          CONFIG_PACKAGE_mariadb-client=y	
          CONFIG_PACKAGE_mariadb-client-extra=y	
          CONFIG_PACKAGE_php7-mod-calendar=y	
          CONFIG_PACKAGE_php7-mod-ctype=y	
          CONFIG_PACKAGE_php7-mod-curl=y	
          CONFIG_PACKAGE_php7-mod-dom=y	
          CONFIG_PACKAGE_php7-mod-exif=y	
          CONFIG_PACKAGE_php7-mod-fileinfo=y	
          CONFIG_PACKAGE_php7-mod-ftp=y	
          CONFIG_PACKAGE_php7-mod-gd=y	
          CONFIG_PACKAGE_php7-mod-gettext=y	
          CONFIG_PACKAGE_php7-mod-gmp=y	
          CONFIG_PACKAGE_php7-mod-hash=y	
          CONFIG_PACKAGE_php7-mod-iconv=y	
          CONFIG_PACKAGE_php7-mod-intl=y	
          CONFIG_PACKAGE_php7-mod-json=y	
          CONFIG_PACKAGE_php7-mod-ldap=y	
          CONFIG_PACKAGE_php7-mod-session=y	
          CONFIG_PACKAGE_php7-mod-mbstring=y	
          CONFIG_PACKAGE_php7-mod-opcache=y	
          CONFIG_PACKAGE_php7-mod-openssl=y	
          CONFIG_PACKAGE_php7-mod-pcntl=y	
          CONFIG_PACKAGE_php7-mod-phar=y	
          CONFIG_PACKAGE_php7-pecl-redis=y	
          CONFIG_PACKAGE_php7-mod-session=y	
          CONFIG_PACKAGE_php7-mod-shmop=y	
          CONFIG_PACKAGE_php7-mod-simplexml=y	
          CONFIG_PACKAGE_php7-mod-snmp=y	
          CONFIG_PACKAGE_php7-mod-soap=y	
          CONFIG_PACKAGE_php7-mod-sockets=y	
          CONFIG_PACKAGE_php7-mod-sqlite3=y	
          CONFIG_PACKAGE_php7-mod-sysvmsg=y	
          CONFIG_PACKAGE_php7-mod-sysvsem=y	
          CONFIG_PACKAGE_php7-mod-sysvshm=y	
          CONFIG_PACKAGE_php7-mod-tokenizer=y	
          CONFIG_PACKAGE_php7-mod-xml=y	
          CONFIG_PACKAGE_php7-mod-xmlreader=y	
          CONFIG_PACKAGE_php7-mod-xmlwriter=y	
          CONFIG_PACKAGE_php7-mod-zip=y	
          CONFIG_PACKAGE_php7-pecl-dio=y	
          CONFIG_PACKAGE_php7-pecl-http=y	
          CONFIG_PACKAGE_php7-pecl-libevent=y	
          CONFIG_PACKAGE_php7-pecl-propro=y	
          CONFIG_PACKAGE_php7-pecl-raphf=y	
          CONFIG_PACKAGE_redis=y	
          CONFIG_PACKAGE_snmpd=y	
          CONFIG_PACKAGE_snmp-mibs=y	
          CONFIG_PACKAGE_snmp-utils=y	
          CONFIG_PACKAGE_zoneinfo-core=y	
          CONFIG_PACKAGE_zoneinfo-asia=y	
          CONFIG_PACKAGE_php7-mod-imagick=y	
          CONFIG_PACKAGE_imagemagick=y	
          CONFIG_PACKAGE_imagemagick-jpeg=y	
          CONFIG_PACKAGE_imagemagick-png=y	
          CONFIG_PACKAGE_imagemagick-tiff=y	
          CONFIG_PACKAGE_imagemagick-tools=y
          EOF

          # LuCI主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          # CONFIG_PACKAGE_luci-theme-netgear=y
          EOF

          # 常用软件包:
          cat >> .config <<EOF
          CONFIG_PACKAGE_curl=y
          # CONFIG_PACKAGE_htop=y
          # CONFIG_PACKAGE_nano=y
          # CONFIG_PACKAGE_screen=y
          # CONFIG_PACKAGE_tree=y
          # CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_wget=y
          EOF

          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_VMDK_IMAGES is not set
          EOF

          # 
          # ========================固件定制部分结束========================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload config.seed
        uses: actions/upload-artifact@master
        with:
          name: config.seed
          path: ./bin/targets/*/*/config.seed

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
